### ISSUE TITLE
使用ldaps提示Can't contact LDAP server

### ISSUE THREAD

**Issue by mrzhxl** [twoBxx/zentao-ldap-plugin#1]
禅道版本是docker开源版18.8
LDAP服务器是微软AD
![image](https://github.com/twoBxx/zentao-ldap-plugin/assets/15653783/c5af7076-b3f5-45bc-a7a1-f25e34e8a401)
日志显示：
13:45:05 Creating default object from empty value in /data/zentao/extension/custom/ldap/lang/zh-cn.php on line 28 when visiting ldap-setting
13:45:05 Undefined offset: 3 in /apps/zentao/module/admin/model.php on line 430 when visiting ldap-setting
13:45:07 Creating default object from empty value in /data/zentao/extension/custom/ldap/lang/zh-cn.php on line 28 when visiting ldap-test
13:45:07 ldap_bind(): Unable to bind to server: Can't contact LDAP server in /data/zentao/extension/custom/ldap/model.php on line 10 when visiting ldap-test
13:45:07 ldap_close(): supplied resource is not a valid ldap link resource in /data/zentao/extension/custom/ldap/model.php on line 14 when visiting ldap-test

**Comment by mrzhxl** [comment]
AD自签证书，已经加信任根证书里
openssl s_client -connect  ldap服务器地址:636
<img width="1090" alt="image" src="https://github.com/twoBxx/zentao-ldap-plugin/assets/15653783/d714aac2-ea9d-425d-9684-af1b22b7bece">

**Comment by twoBxx** [comment]
> 禅道版本是docker开源版18.8 LDAP服务器是微软AD ![image](https://private-user-images.githubusercontent.com/15653783/278548791-c5af7076-b3f5-45bc-a7a1-f25e34e8a401.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyNDEwNjYsIm5iZiI6MTcwMTI0MDc2NiwicGF0aCI6Ii8xNTY1Mzc4My8yNzg1NDg3OTEtYzVhZjcwNzYtYjNmNS00NWJjLWE3YTEtZjI1ZTM0ZThhNDAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI5VDA2NTI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNzI4NTliZjY1OWNhZTExNzFlODU4ODE3MDZmOGZlMGMwNDY5NTYxODlmM2Q0MmJiMmNiOTg2MjNmZGUzMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M2kqyEiu77ZYF2o6h6SjunReFRbi3fG0zdH3yFZVSTc) 日志显示： 13:45:05 Creating default object from empty value in /data/zentao/extension/custom/ldap/lang/zh-cn.php on line 28 when visiting ldap-setting 13:45:05 Undefined offset: 3 in /apps/zentao/module/admin/model.php on line 430 when visiting ldap-setting 13:45:07 Creating default object from empty value in /data/zentao/extension/custom/ldap/lang/zh-cn.php on line 28 when visiting ldap-test 13:45:07 ldap_bind(): Unable to bind to server: Can't contact LDAP server in /data/zentao/extension/custom/ldap/model.php on line 10 when visiting ldap-test 13:45:07 ldap_close(): supplied resource is not a valid ldap link resource in /data/zentao/extension/custom/ldap/model.php on line 14 when visiting ldap-test

我这边没有测试过ldaps的操作，查阅 [php ldap](https://www.php.net/manual/en/function.ldap-bind.php) 的文档之后发现，目前的 `ldap_connect($host,$port)` 似乎存在一些问题，需要使用 `ldap_connect("ldaps://ldap.test.com:636")` 的方式。
不过目前只有测试方法使用了，理论来讲，不影响同步，可以试试修改 `ldap/model.php` 文件第 7 行中的 `ldap_connect` 的url拼接
