### ISSUE TITLE
Consult Windows ad searchDN Settings

### ISSUE THREAD

**Issue by bbotte** [twoBxx/zentao-ldap-plugin#2]
请教Windows ad searchDN的设置
连接测试ok，searchDN这里试了好多次，点击 “手动同步” 提示“同步了0位用户信息”
memberOf=CN=zentao,OU=IT,dc=test,dc=com
(&(sAMAccountName={0})(memberOf=CN=zentao,OU=IT,dc=test,dc=com))

不知道正确的怎么填写，searchDN 是在BindDN基础上搜索吗

**Comment by bbotte** [comment]
SELECT * FROM zentao.zt_usergroup;

**Comment by bbotte** [comment]
searchDN 写 CN=zentao,OU=IT,dc=test,dc=com ，“手动同步” 提示“同步了1位用户信息”
SELECT * FROM zentao.zt_usergroup;
account    group  project
________       2          null
SELECT * FROM zentao.zt_user;
没有同步的用户
再同步提示 Duplicate entry for key account, the sql is : insert into zt_usergroup

**Comment by twoBxx** [comment]
> searchDN 写 CN=zentao,OU=IT,dc=test,dc=com ，“手动同步” 提示“同步了1位用户信息” SELECT * FROM zentao.zt_usergroup; account group project ________ 2 null SELECT * FROM zentao.zt_user; 没有同步的用户 再同步提示 Duplicate entry for key account, the sql is : insert into zt_usergroup

麻烦开启debug日志看下日志输出信息，看sql报错的话，是账号同步过去了，然后数据重复

**Comment by twoBxx** [comment]
> 请教Windows ad searchDN的设置 连接测试ok，searchDN这里试了好多次，点击 “手动同步” 提示“同步了0位用户信息” memberOf=CN=zentao,OU=IT,dc=test,dc=com (&(sAMAccountName={0})(memberOf=CN=zentao,OU=IT,dc=test,dc=com))
> 
> 不知道正确的怎么填写，searchDN 是在BindDN基础上搜索吗



> 请教Windows ad searchDN的设置 连接测试ok，searchDN这里试了好多次，点击 “手动同步” 提示“同步了0位用户信息” memberOf=CN=zentao,OU=IT,dc=test,dc=com (&(sAMAccountName={0})(memberOf=CN=zentao,OU=IT,dc=test,dc=com))
> 
> 不知道正确的怎么填写，searchDN 是在BindDN基础上搜索吗

`Search DN` 指的是用户搜索域
`Bind DN` 指的是管理员登录账号和 `BindDN 密码` 是配合使用登录 `LDAP` 的
重复的问题是因为不熟悉 php 语言，导致的一个bug，目前是修复了分组的，麻烦使用最新源码中的 `package.sh` 打包使用
